# -*- coding: utf-8 -*-
"""Lab03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hcnACLLQBfwH6-SdifPOV9qTDe61308d
"""

#Exercise 1
#a
print("D is 'fish'")
print("P is 'need water to servive'")
print("Formal  form: For all x in D, P(x)\n")
#b
print("D is 'a person'")
print("P is 'is left handed'")
print("Formal form: Exist a x in D, P(x)\n")
#c
print("D is 'an employee in the company'")
print("P is 'is late to work everyday'")
print("Formal form: Exist an x in D, P(x)\n")
#d
print("D is 'fishes in this pond'")
print("P is 'are Koi fish'")
print("Formal  form: For all x in D, P(x)\n")
#e
print("D is 'creature in the ocean'")
print("P is 'can live on land'")
print("Formal form: Exist a x in D, P(x)\n")
#f
print("D is 'students in class A'")
print("P is 'did not pass the test'")
print("Formal  form: For all x in D, P(x)\n")

#Exercise 2
S = ['For all fishes, they need water to survive',
     'Exist a person, who is left handed',
     'Exist an employee in the company, who is late to work everyday',
     'For all fishes in this pond, they are Koi fish',
     'There is at least one creature in the ocean, it can live on land',
     'Every students in class A did not pass the test'
     ]


def formalConvert(S):
    if ', ' not in S:
        return ["Invalid statement", "Invalid statement", "Invalid statement"]

    parts = S.split(', ')

    D = parts[0].split(' ', 2)[2]
    P = parts[1].split(' ', 1)[1]

    if 'For all' in parts[0]:
        F = f"For all x in {D}, {P}(x)"
    else:
        F = f"There exists x in {D} such that {P}(x)"

    return [D, P, F]


for s in S:
    print(formalConvert(s))

#Exercise 3
#a
print("'D is 'people'")
print("P is 'blond'")
print("Q is 'is westerners'")
print("Formal form: For all x in D, P(x) then Q(x)\n")
#b
print("'D is 'people'")
print("P is 'hair is black'")
print("Q is 'is a westerners'")
print("Formal form: Exist x in D, P(x) then Q(x)\n")
#c
print("'D is 'student'")
print("P is 'study correctly'")
print("Q is 'high score'")
print("Formal form: For all x in D, P(x) then Q(x)\n")
#d
print("'D is 'mammal'")
print("P is 'live in the sea'")
print("Q is 'is either dolphins or whales'")
print("Formal form: For all x in D, P(x) then Q(x)\n")
#e
print("'D is 'bird'")
print("P is 'don’t have wings and can swim'")
print("Q is 'is penguins'")
print("Formal form: For all x in D, P(x) then Q(x)\n")
#f
print("'D is 'bird'")
print("P is 'have wing'")
print("Q is 'can't fly'")
print("Formal form: Exist x in D, P(x) then Q(x)\n")

#Exercise 4

def nega(A):
  N = A.replace("all", "no").replace("Exist", "For all").replace("not", "").replace("then", "and")
  return N

print(nega("For all fishes, they need water to survive."))
print(nega("Exist a person, who is left handed"))
print(nega("Exist an employee in the company, who is late to work everyday."))
print(nega("For all fishes in this pond, they are Koi fish."))
print(nega("There is at least one creature in the ocean, it can live on land"))

#Exercise 5

def nega(S):
    temp = S.split(',')
    D = temp[0].strip()
    P = temp[1].strip()

    D = D.replace("For all ", '').replace("Exist ", '').replace("There is at least ", '').strip()

    if len(D.split(' ')) == 2:
        D = D.split(' ', 1)[1]
    elif D.endswith('s'):
        D = D[:-1]

    P = P.split(' ', 1)[1].strip()
    P1 = P.split(' ')

    fForm = ""
    if "For all" in S:
        fForm = "Exist " + D + ", " + P1[0] + " not " + P
    elif "Exist" in S or "There is at least" in S:
        fForm = "For all " + D + ", " + P1[0] + " not " + P
        fForm = fForm.replace(" one ", " ").replace(" an ", " ")

    return fForm


print("'a)")
print(nega("For all fish, they need water to survive."))
print("'b)")
print(nega("Exist a person, who is left-handed"))
print("'c)")
print(nega("Exist an employee in the company, who is late to work every day."))
print("'d)")
print(nega("For all fish in this pond, they are Koi fish."))
print("'e)")
print(nega("There is at least one creature in the ocean, it can live on land"))

#Exercise 6

print("Negation: There is a person, who is blond and is not a westerner.")
print("Contrapositive: For all people, if they are not westerners then they are not blond.")
print("Converse: For all people, if they are westerners then they are blond.")
print("Inverse: For all people, if they are not blond then they are not westerners.")

print("\nNegation: There is a person, whose hair is black and is not a westerner.")
print("Contrapositive: For all people, if they are not westerners then their hair is not black.")
print("Converse: For all people, if their hair is black then they are westerners.")
print("Inverse: For all people, if they are not westerners then their hair is not black.")

print("\nNegation: There is a student, who studies correctly and does not have high score.")
print("Contrapositive: For all students, if they do not have high score then they did not study correctly.")
print("Converse: For all students, if they have high score then they studied correctly.")
print("Inverse: For all students, if they did not study correctly then they do not have high score.")

print("\nNegation: There is a mammal, who lives in the sea and is neither a dolphin nor a whale.")
print("Contrapositive: For every mammal, if they are not a dolphin or a whale then they do not live in the sea.")
print("Converse: For every mammal, if they are a dolphin or a whale then they live in the sea.")
print("Inverse: For every mammal, if they do not live in the sea then they are neither a dolphin nor a whale.")

print("\nNegation: There is a bird, who does not have wings and can swim but is not a penguin.")
print("Contrapositive: For every bird, if they are not a penguin then they have wings or cannot swim.")
print("Converse: For every bird, if they are a penguin then they don't have wings and can swim.")
print("Inverse: For every bird, if they have wings or cannot swim then they are not penguins.")

print("\nNegation: For all bird, they have wings and can fly.")
print("Contrapositive: For all birds, if they cannot fly then they do not have wings.")
print("Converse: For all birds, if they can fly then they have wings.")
print("Inverse: For all birds, if they do not have wings then they cannot fly.")