# -*- coding: utf-8 -*-
"""Lab04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2dzh5gD1jivePnyriTFjFzcSlUttehF
"""

#Exercise 1
print("a) Valid")
print("b) InValid")
print("c) Valid")
print("d) Valid")

#Exercise 2
import math
#a
for x in range(101):
    if x**2 == 15**2 + 16**2:
        print("The given statement is correct when x is equal to", x)
        break
else:
    print("The given statement is incorrect for all values of x within the given domain.")

#b
for x in range(101):
    if x**2 == 12**2 + 16**2:
        print("The given statement is correct when x is equal to", x)
        break
else:
    print("The given statement is incorrect for all values of x within the given domain.")

#c
for x in range(-50, 51):
    if x**2 >= 99*x:
        print("The given statement is correct when x is equal to", x)
        break
else:
    print("The given statement is incorrect for all values of x within the given domain.")

#d
for x in range(50, 100):
    if x*(x+1)*(x+2)%6 != 0:
        print("The given statement is correct when x is equal to", x)
        break
else:
    print("The given statement is incorrect for all values of x within the given domain.")

#e
for x in range(101):
  for y in range(101):
    if math.sqrt(x+y) == math.sqrt(x) + math.sqrt(y):
        print("The given statement is correct when x is equal to", x)
        break
  else:
    continue
  break
else:
    print("The given statement is incorrect for all values of x within the given domain.")

#Exercise 3
#a
print("a) ∃x ∈ Z, 0 <= x <= 100 such that x^3 < x")
for x in range(101):
    if  x**3 < x:
        print("The given statement is Incorrect")
        break
else:
    print("The given statement is Correct")

#b
print("b) ∃x ∈ Z, 0 <= x <= 100 and x is even such that x*3+1 is not a prime number")
def is_prime(n):
    if n <= 1:
        return False
    elif n <= 3:
        return True
    elif n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

for x in range(101):
    if  (is_prime(x*3+1) and x % 2 == 0) :
        print("The given statement is Incorrect")
        break
else:
    print("The given statement is Correct")

#c
print("c) ∃x ∈ Z, 1 <= x <= 100 and x is even such that x*5+3 is not a prime number")

for x in range(100):
    if  (is_prime(x*5+3) and x % 2 == 0) :
        print("The given statement is Incorrect")
        break
else:
    print("The given statement is Correct")

#d
print("d) ∃x ∈ Z, 0 < c <= 100, c % 4 = 0 such that ∀a,b ∈ Z+, c**2 != a**2 + b**2")
for c in range(100):
  if (c % 4 == 0):
    for a in range(1, c):
      for b in range(1, c):
        if (c**2 == a**2 + b**2):
          print("The given statement is Correct")
          break
      else:
        continue
      break
    else:
        continue
    break
else:
    print("The given statement is Incorrect")

#d
print("d) ∃x ∈ Z, 0 < c <= 100, c % 5 = 0 such that ∀a,b ∈ Z+, c**2 != a**2 + b**2")
for c in range(100):
  if (c % 5 == 0):
    for a in range(1, c):
      for b in range(1, c):
        if (c**2 == a**2 + b**2):
          print("The given statement is Correct")
          break
      else:
        continue
      break
    else:
        continue
    break
else:
    print("The given statement is Incorrect")

#f
print("∀c ∈ Z, 0 < c <= 100 such that c**2 > c")
for c in range(100):
  if (c**2 <= c):
    print("The given statement is Correct")
    break
else:
    print("The given statement is Incorrect")

#Exercise 4
#a
print("a)")
suma1 = 0
suma2 = 0
for x in range(11):
  for y in range(11):
    suma1 = suma1 = (x+y)**2
    suma2 = suma2 = (x+2*y)**2
if (suma1 > suma2):
  print("Correct")
else:
  print("Incorrect")

#b
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

print("b")
sumb = 0
for x in range(11):
  sumb = sumb + factorial(x)
if (sumb <= factorial(20)):
  print("Incorrect")
else:
  print("Correct")

#c
print("c")
sumc = 0
for x in range(11):
  sumc = sumc + 3*x*x
if (sumc <= 10**3):
  print("Incorrect")
else:
  print("Correct")

#d
print("d)")
sumd = 0
for x in range(5, 11, 1):
  sumd = sumd + 4**3 + 6**2 + 2*x
if (sumd <= (10**4 + 2*10*10*10 + 10*10 -5**4 -2*5*5*5 -5**2)):
  print("Incorrect")
else:
  print("Correct")

#Exercise 5
print("a) Valid")
print("b) Invalid")
print("c) Valid")
print("d) Valid")